apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tamilzh2018/boutique-gitops.git
    targetRevision: HEAD
    path: boutique

  destination:
    server: https://kubernetes.default.svc
    namespace: boutique

  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
